### PR TITLE
Add assists

### PR DESCRIPTION
**Pull request by nstarman**
Signed-off-by: nstarman <nstarkman@protonmail.com>

TODO:
- [x] docs
- [x] tests
- [x] changelog

Followup:  Assemble lists of numpy functions with similar inputs & outputs so that overloads can be done with a for loop (or better yet ``@assists(func, ...)`` can accept the whole list).

## Description

``implements`` is for a single numpy func. ``assists`` allows for abstraction over many different numpy funcs with similar inputs & outputs.

```python
VEC_FUNCS = NumPyOverloader()

@dataclass
class Vector1D(overload_numpy.NDFunctionMixin):
    """A simple array wrapper."""

    x: np.ndarray
    NP_FUNC_OVERLOADS: ClassVar[NumPyOverloader] = VEC_FUNCS


array = np.arange(10)
vec1d = Vector1D(array)

@VEC_FUNCS.assists(np.concatenate, types=Vector1D, dispatch_on=Vector1D)
def concatenate_assists(dispatch_on, func, vecs: tuple[Vector1D, ...], *args, **kwargs):
    cls = type(vecs[0])
    if any(not isinstance(type(v), cls) for v in vecs):
            return NotImplemented
    return cls(*(func(tuple(getattr(v, f.name) for v in vec1ds), *args, **kwargs)
                     for f in fields(cls)))

# a bad example because these are ufuncs (not yet supported) and also this is not how vectors work.
@VEC_FUNCS.assists(np.subtract, types=Vector1D, dispatch_on=Vector1D)
@VEC_FUNCS.assists(np.add, types=Vector1D, dispatch_on=Vector1D)
def concatenate_assists(dispatch_on, func, vec1: Vector1D, vec2: Vector1D, *args, **kwargs):
    cls = type(vec1)
    if type(vec2) is not cls:
        return NotImplemented
    return cls(*(func(tuple(getattr(v, f.name) for v in vec1ds), *args, **kwargs)
                     for f in fields(cls)))
```

## PR Checklist

- [ ] Check out the [contributing guidelines](https://github.com/astropy/astropy/blob/master/CONTRIBUTING.md) and [code of conduct](https://github.com/astropy/astropy/blob/master/CODE_OF_CONDUCT.md)
- [ ] Check out the [contributing workflow](http://docs.astropy.org/en/latest/development/workflow/development_workflow.html) ( for a practical example [click here](https://docs.astropy.org/en/latest/development/workflow/git_edit_workflow_examples.html#astropy-fix-example) )
- [ ] Give a detailed description of the PR above.
- [ ] Document changes in the `CHANGES.rst` file. See existing changelog for examples.
- [ ] Add tests, if applicable, to ensure code coverage never decreases.
- [ ] Make sure the docs are up to date, if applicable, particularly the docstrings and RST files in `docs` folder.
- [ ] Ensure linear history by rebasing, when requested by the maintainer.

### CODE REVIEW

**Comment by nstarman** [comment]
@mhvk, hi! I thought you might be interested in this repository. I'm working to centralize how I / others can overload ``__numpy_function__`` and ``__numpy_ufunc__`` (latter not yet implemented). I compile almost the whole project with ``mypyc`` and upload those wheels to PyPi, so this should be very fast (speed tests not yet implemented).

**Comment by mhvk** [comment]
Yes, that could work. I thought a little about this when I was implementing the helpers for `Masked`, since I thought that having done them for `Quantity`, there surely was a lot in common. In the end, it was really not that much: in the end, dealing with masks really is different from dealing with units. So, I'm not so sure that going beyond allowing for categories of helpers, as I did for `Quantity` and `Masked` is going to do much...  But I'm happy to be proven wrong! It may also be that different storage options (`dask`, `xarray`) have much more in common -- did you check their implementations?

p.s. Just a reminder that it is `__array_function__` and `__array_ufunc__`, not `__numpy_*__`

**Comment by nstarman** [comment]
Oops. Thanks. It's in the code correctly, but not in places in the documentation.

**Comment by nstarman** [comment]
Part of my suggestion is adapting how `Quantity` and `Mask` overloads are done. Basically just using new ``assists`` functions, like in the example above. I think this will offer a speed boost (this should of course be tested).
I've been reviewing some other ndarray consumer libraries. ``pint`` actually has a mechanism similar to this PR and has  helper categories and in quick tests their unit library is faster than ours.
Even if `Quantity` and `Mask` are not changed, it would be great to offer fuller numpy interoperability for many more objects in Astropy. I mentioned Representation, but also BaseCoordinateFrame and SkyCoord, Time, etc.  I use this library in my own stuff and it works for everything.

**Pull request merged**
